### ISSUE TITLE
Can I synchronize the Player view?

### ISSUE THREAD

**Issue by eggham0518** [Rygelouv/android-audio-sensei#4]
Can I synchronize the Player view running in the service with the Player view of the activity?

There is a player playing in the service for background playback. I'm looking for a way to synchronize it with an activity's player when the user opens the activity again,

I hope you can help me.

The way I tried.

Static PLAY_SERVICE;

-------
MainActivity
@onCreate
if(isServiceRunning ==true){
 audioplayerView = PLAY_SERVICE.audioplayerView;

audioplayerView .play(); //It is possible to control through the method, but not through the player view of the activity.

}

**Comment by eggham0518** [comment]
I found a solution. Just use addView.

**Comment by rygelouv** [comment]
@eggham0518 I'm glad you figure that out. I will take this in account for the next release and maybe come up with a better solution. 
I'm closing the issue for now.
